CREATE TABLE IF NOT EXISTS store_manager (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone CHAR(13) NOT NULL UNIQUE,
    company INT,
    FOREIGN KEY (company) REFERENCES company(id) ON UPDATE CASCADE ON DELETE SET NULL
);