CREATE TABLE IF NOT EXISTS user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(13) NOT NULL UNIQUE,
    password CHAR(60) NOT NULL,
    user_type ENUM('ADMIN','STORE_ADMIN','STORE_STAFF') NOT NULL DEFAULT 'STORE_STAFF',
    company INT,
    store_branch INT,
    FOREIGN KEY (company) REFERENCES company(id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (store_branch) REFERENCES store_branch(id) ON UPDATE CASCADE ON DELETE SET NULL
);
